### PR TITLE
Custom keyboard added

### LINKED ISSUE #104: Safe: Passwd input need Polkawallet Safe keyboard.
Encapsulates a separate security keyboard for password or private key input.

### PR DESCRIPTION
**Pull request by agutsal**
@jiangfuyao please, review  

close #104

### CODE REVIEW

**Comment by Web3Foundation** [comment]
@agutsal once you submit work in gitcoin i'll be able to pay out, thanks for all the help on this one!

**Comment by agutsal** [comment]
@Web3Foundation have difficulties topping up my Metamask ETH account with small amount to pay for submit transaction. Exchange where I've purchased ETH for that stopped operations for 72 hours (security period). If you wish, you can help me sending 20 cents in ETH here:  0x6c7623Eed8fb55dE471B3AfA2f44afcC2e2946d4

Would be thankful ;)

**Comment by Web3Foundation** [comment]
@agutsal no problem

**Comment by agutsal** [comment]
@Web3Foundation Thanks for letting me know about faucet. I've received your donation and submitted work on Gitcoin.

**Comment by Web3Foundation** [comment]
Great @agutsal thanks for the great job; paid out.

**Pull request merged**
