### PR TITLE
Keyboard added, input is handled

### PR DESCRIPTION
**Pull request by agutsal**
Basically it's partially finished for name TextInput, but I'd like to discuss keyboard flickering. According to [this](https://github.com/facebook/react-native/issues/14045) thread that won't be possible to fix for current React-Native version. Solution is to use custom controls in place of TextInput, but this would require more research and work. Please, lemme know.

### CODE REVIEW

**Comment by jiangfuyao** [comment]
@agutsal Hey, Nice to see these. I will to try it. Really need a custom control replacement TextInput.

**Comment by agutsal** [comment]
@jiangfuyao this is another big task. I'm assured every custom control will hit `Keyboard.arise()` or whatever is the method name without an option to control that. We should a) either find out some which won't b) fork some open source control, fix that and maintain it.

I'd prefer to finish this one first (attach what we have to password items, fix some UI stuff) then close that project then start new one.

**Comment by jiangfuyao** [comment]
@agutsal Now in the early stages of the project, use the a) solution first.

**Comment by agutsal** [comment]
Check this: https://github.com/halilb/react-native-textinput-effects

Currently I'm checking how does they handle Keyboard.

**Comment by agutsal** [comment]
@jiangfuyao solution above won't work as they use TextItem internally. This seems to be better one: https://github.com/themodernjavascript/react-native-custom-keyboard-kit

Since it was not requested initially to replace controls, don't you mind adding 100 DAI to current project, @jiangfuyao ?

I'm working on solution 2 now, hopefully will get it done by the end of the day.

**Comment by agutsal** [comment]
@jiangfuyao #130 updated. Please try custom numeric keyboard for Name input. Let me know.

**Comment by agutsal** [comment]
[react-native-custom-keyboard-kit](https://github.com/themodernjavascript/react-native-custom-keyboard-kit) seems to be pretty buggy also. Unmaintainable and hardly use Java inside. Will let you try, then reverting back to old implementation and waiting you to discuss, @jiangfuyao

**Comment by jiangfuyao** [comment]
react-native-custom-keyboard-kit is not a good implementation.

**Comment by agutsal** [comment]
@jiangfuyao `git push --force` to previous one. I said - that's another big task to find the right approach/library. That was not planed from the beginning.

**Comment by agutsal** [comment]
Reverted. I'll finish what we have now. Just wasted 5 hours today on `react-native-custom-keyboard-kit`, damn.

**Comment by jiangfuyao** [comment]
Maybe this is good: 
<https://www.jianshu.com/p/6b6879323069>  
<https://github.com/zhuanghongji/page/issues/7>  
<https://github.com/lyxia/react-native-yusha-customKeyboard>

**Comment by agutsal** [comment]
@jiangfuyao lemme try their demo

**Comment by agutsal** [comment]
@jiangfuyao this one works for me. Lemme add this implementation

**Comment by agutsal** [comment]
@jiangfuyao #130 updated. Looks good to me (added to first input only yet)

**Comment by agutsal** [comment]
@jiangfuyao thanks for that link btw ;)

**Comment by jiangfuyao** [comment]
Now, full support for all inputs. Then I will check and merge. Thanks.

**Comment by agutsal** [comment]
Both passwords are there already. Regarding first control - I doubt they support multi-line, but will check shortly.

**Comment by agutsal** [comment]
Key component is now custom also, @jiangfuyao 
Check it.

**Comment by jiangfuyao** [comment]
Note: other pages also have the input box.

**Comment by agutsal** [comment]
Noted. There are 49 more such entries. Since original project stated only password and private key inputs
image
I'd consider these 49 entries Phase II. Sounds fair?

**Comment by jiangfuyao** [comment]
@agutsal The other pages only password need the safe keyboard.

**Comment by agutsal** [comment]
@jiangfuyao check this one

**Comment by agutsal** [comment]
These both are related:
https://github.com/lyxia/react-native-yusha-customKeyboard/issues/13

I can try using another repo for that component with that issue fixed, but we'll have system keyboard flickering again.

**Comment by agutsal** [comment]
@jiangfuyao  Check recent commit (CreateAccount screen). It's still not perfect, keyboard is flickering, but system keyboard gets dismissed once shown. As I already said there's no perfect solution on that ReactNative version. We should come to some agreement.

**Comment by agutsal** [comment]
@jiangfuyao If you reviewed my recent commit I'd like to know your thoughts.

**Comment by agutsal** [comment]
[clabot:check]

**Comment by jiangfuyao** [comment]
@agutsal I will try it.

**Comment by agutsal** [comment]
@jiangfuyao thx

**Comment by jiangfuyao** [comment]
The 2th issue is fixed, but 1th not. On the android, the custom keyboard has no focus function.

**Comment by agutsal** [comment]
@jiangfuyao I've found [that](https://github.com/APSL/react-native-keyboard-aware-scroll-view) component. Hopefully it will do what you need. Will buzz you once I update the code.

**Comment by agutsal** [comment]
@jiangfuyao seems autofocus works now.

**Comment by jiangfuyao** [comment]
@agutsal Testing...

**Comment by jiangfuyao** [comment]
@agutsal Is nice, I will to merge this after resolved conflicts.

**Comment by agutsal** [comment]
@jiangfuyao from what I see there are conflicting files. Conflicts are caused Windows CRLF symbol in the end of each line. Since that's Windows-only EOL symbol, Git suggests not to commit it. This could be changed with help from [here](https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings). However, if you want to keep CRLF EOL symbol, I'll re-configure my git to add it to each line and will try merging again.

Let me know.

**Comment by jiangfuyao** [comment]
@agutsal Keep it, and I'll delete it later version, thanks!

**Comment by agutsal** [comment]
@jiangfuyao that's not correct decision. I've analyzed what have broken things and found, that your recent commit b4a3b0badc911aa90c2abe20e1ed7fe7feb30ab0 (that' merged PR #135) did so.
PR #135 has 18k changed lines, not because it's super cool mega commit, but because its author(s) has changed `CR` to `CRLF` everywhere in codebase. I'm wondered how git `pre-commit` hook (that use `husky` that required `lint` npm script execution allowed so), perhaps husky was just temporarily switched off by committer, otherwise it would `--fix` all sources, replacing `CRLF` back to `CR` everywhere. Now, if I follow your commands we would have problems. I'd suggest to reset to 0d282ef0a333ba04e918a9fe2d79df571db14fb9 (reverting #135 PR), `push --force` then fix #135 and merge it back. Then I can easily push my changes.

If not - everyone who is currently working on your code will have the same problems I have now.

**Comment by jiangfuyao** [comment]
@agutsal I changed EOL from `CRLF` to `LF`, https://github.com/polkawallet-io/polkawallet-RN/pull/137  
this is your `master` branch to pull polkawallet-RN `fix-eol` branch, just for test. Is it ok now? Only can use `CR`?

**Comment by agutsal** [comment]
Trying. Will let you know shortly @jiangfuyao

**Comment by agutsal** [comment]
@jiangfuyao that was a nice talk. I'm closing that pull request, patched recent `origin/fix-eol` branch and created new PR

**Pull request closed without merging**
