### PR TITLE
[WIP] Use sr25519 to create account

### LINKED ISSUE #111: keyring: Use the Schnorrkel/Ristretto x25519 (sr25519)
- Create account will use the 'sr25519';  
- Remove support for ’ed25519‘;

### PR DESCRIPTION
**Pull request by touhonoob**
to resolve #111 

- [x] use sr25519 to create account in place of ed25519
- [x] test with android emulator
- [ ] test with ios emulator
- [x] test account export/import
```
12 Word Mnemonic
{"address":"5HTE8n3WPvioMuSvCm7wWKMP8whJgq713CuNx194qMVJQRnC","encoded":"0x7b21f7c77f042ed76331bdde14521a03196de39a1de9cf46dbbeda1ca9647e9eb1e414575bf94f80e69482f46e526db264b67b5caa00cb530edaedf4446c1d71a61fef82cdcab922c07cd240b815265ee8988c74a214064f0c1ac0475bf531cf6f94697a293304dc8f823c0900a80899258c0ef325be0ea6679907461f05793d15f971a92f7094abfc6ec7d25b52f2ae10f227c333f5afdb6ca789469f","encoding":{"content":["pkcs8","sr25519"],"type":"xsalsa20-poly1305","version":"2"},"meta":{"name":""}}

24 Word Mnemonic
{"address":"5FHS2zEZbf32u5pYuHwaXSduSV9r1AbF7jbVQkj38sBZgYmo","encoded":"0x15f1ee208d080c4a6992f7159cd9b047e8a52c7cd533d04d0dfa601ac8da8fbcd727daf614cec053182517895294964b3bb68febe9c1c6c56aca076500f7741e413c23f4860d2488e2c25d20ed7cb75b35b2a583ddfb5224728476c1bd848f8fc3d1eac49d5fe78921040fa443c52f5431f3a11c7439e1a50c712a1de221ac244fc6c0fb062f2210c9019ee7077f2d749bf50e270fb5859eb69cdc6f48","encoding":{"content":["pkcs8","sr25519"],"type":"xsalsa20-poly1305","version":"2"},"meta":{"name":""}}

Raw Seed
{"address":"5E1cy6bxDUn4GgX5UMLgmuin7eXxdH6K5VBVLEKUMYM7xBR5","encoded":"0x5d871aed4dafbb784ffe1ac8c42dcb81cd25163a07af0ef69cf76b0d892d49edc5ccae9cb101504ad11dd1b43533c45938ed92408552a46bcc5e87a90691f9b192a2fcc1876328eacbe296540a720055e0ac70cffe9af62c9b2cb519726cb625ac40abc0dad0ff0515aa1a0c78aab7ae1e3589021dadb22fdf7c8c02d78b685da82a036cdb0b23870327a91d4b048385ee63198f790e0d72fd9eb3bb6b","encoding":{"content":["pkcs8","sr25519"],"type":"xsalsa20-poly1305","version":"2"},"meta":{"name":""}}
```

### CODE REVIEW

**Comment by touhonoob** [comment]
JavaScriptCore runtime of react-native doesn't support WebAssembly

**Comment by Web3Foundation** [comment]
@touhonoob so you can't work on this issue anymore? @jiangfuyao to confirm details.

**Comment by jiangfuyao** [comment]
This is a thorny problem, but there are ways to solve it. Just as the first time to integrate the polkadot api into a react native, it was not possible at that time. So, I will adjust the time to solve this, this is not an impossible task.

**Comment by jiangfuyao** [comment]
I have studied this problem with @jacogr. There are some directions

**Comment by Web3Foundation** [comment]
@touhonoob would you be willing to work with @jiangfuyao on this? Didn't want the work you've done so far to go un-rewarded as well.

**Comment by touhonoob** [comment]
@Web3Foundation @jiangfuyao Sorry I don't have spare time for this in the coming weeks. Thanks for the update anyway :)

**Pull request closed without merging**
