### PR TITLE
Fix #56 Transfer: Insufficient balance prompt(include fees check)

### LINKED ISSUE #56: Transfer: Insufficient balance prompt(include fees check)
Need to check the account balance to compare with the transfer balance and the fees

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes #56

### CODE REVIEW

**Comment by iamonuwa** [comment]
What is the formula for calculating the totalFees?

**Comment by jiangfuyao** [comment]
Reference: https://github.com/polkadot-js/apps/blob/master/packages/ui-signer/src/Checks/Transfer.tsx

**Comment by Web3Foundation** [comment]
@iamonuwa Are you still working on this issue after @jiangfuyao advice? Thanks!

**Comment by iamonuwa** [comment]
> @iamonuwa Are you still working on this issue after @jiangfuyao advice? Thanks!

Yes I am. Work in progress

**Comment by Web3Foundation** [comment]
@iamonuwa looks like you stopped work on this bounty, anything else we could learn from your blockers here?

**Comment by Web3Foundation** [comment]
@iamonuwa any update?

**Comment by Web3Foundation** [comment]
@iamonuwa please let us know if you're planning on continuing work on this or not.

**Comment by iamonuwa** [comment]
> @iamonuwa please let us know if you're planning on continuing work on this or not. The bounty is still in a "work submitted" state and we have not hear back from you after "stopping" work.

Apologies, I got busy at my day job. Will commence work if no one picks this up

**Comment by Web3Foundation** [comment]
Great sounds good @iamonuwa please just update as soon as you have a chance :)

**Comment by Web3Foundation** [comment]
@iamonuwa do you still intend to work on this?

**Comment by iamonuwa** [comment]
I'll pass, really busy right now

**Comment by jiangfuyao** [comment]
If there are new developments, please pull new requests.Thanks

**Pull request closed without merging**
